language: python

python: "3.7.3"

services: docker

branches:
    only:
      - master

env:
  global:
    - DATABASE_DSN=postgresql://postgres:postgres@localhost:5432/postgres

cache: pip

before_install: pip install poetry

install: make install

before_script:
    - make database
    - sleep 3

script: make test
