language: python

python:
  - "3.7.3"

services: postgresql
addons:
  postgresql: "11"

env:
  global:
    - DATABASE_DSN=postgresql://postgres:@localhost:5432/postgres

cache: pip

install: make install

script: make test
