language: python

python: "3.7.3"

services: docker

branches:
    only:
      - master

env:
  global:
    - DATABASE_DSN=postgresql://postgres:postgres@localhost:5432/postgres

cache: pip

install: make install

before_script:
    - docker run -d --name db -p 5432:5432 -e POSTGRES_PASSWORD=postgres -e POSTGRES_USER=postgres postgres:11-alpine
    - sleep 3

script: make test
