language: python

python: "3.8.1"

services: docker

branches:
    only:
      - master

env:
  global:
    - PROJECT_NAME=migo
    - MIGO_LOG_LEVEL=WARNING

cache: pip

before_install: pip install poetry

install: make install

before_script:
    - make database
    - sleep 3

script: make test
